version: "3.8"

services:
  immer:
    image: immersspace/immers:latest
    restart: unless-stopped
    ports:
      - 443:8081
      - 80:80
    env_file: '.env'
    environment:
      NODE_ENV: 'production'
    depends_on:
      - mongodb
    volumes:
      - ~/immers:/usr/src/immers/static-ext
    logging:
      driver: local
      options:
        max-size: '10m'
    
  mongodb:
    image: mongo:4.2
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    logging:
      driver: local
      options:
        max-size: '10m'

volumes:
  mongo-data:
