version: "3.8"

services:
  proxy:
    image: valian/docker-nginx-auto-ssl
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    depends_on:
      - immer
    env_file: '.env.nginx'
  immer:
    image: immersspace/immers:latest
    restart: always
    env_file: '.env'
    environment:
      NODE_ENV: 'production'
      proxyMode: 1
      dbString: mongodb://localhost:27017/immers
    depends_on:
      - mongodb
    volumes:
      - ~/immers:/usr/src/immers/static-ext
    logging:
      driver: local
      options:
        max-size: '10m'
    
  mongodb:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    logging:
      driver: local
      options:
        max-size: '10m'

volumes:
  mongo-data:
  ssl_data:
